services:
# POSTGRES DATABASE
  postgres-dev:
    profiles:
      - development
    image: postgres:latest
    environment:
      POSTGRES_DB: simulshift.com
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - ../postgres/.env.development

  postgres-prod:
    profiles:
      - production
    image: postgres:latest
    command: >
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      POSTGRES_DB: simulshift.com
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /etc/letsencrypt/live/backend.simulshift.com/fullchain-docker.pem:/var/lib/postgresql/server.crt:ro
      - /etc/letsencrypt/live/backend.simulshift.com/privkey-docker.pem:/var/lib/postgresql/server.key:ro
      - ${POSTGRES_PRODUCTION}/postgresql.conf:/etc/postgresql/postgresql.conf
      - ${POSTGRES_PRODUCTION}/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    env_file:
      - ../postgres/.env.production

volumes:
  postgres-data:
