services:
  # ENVOY REVERSE PROXY
  envoy-prod:
    profiles:
      - production
      - linux
    image: envoyproxy/envoy:v1.30-latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${ENVOY_PATH_PRODUCTION}/start-envoy.sh:/usr/local/bin/start-envoy.sh
      - ${ENVOY_PATH_PRODUCTION}/envoy_production.yaml:/etc/envoy/envoy.yaml
    ports:
      - "443:443"        # Port for HTTPS traffic
      - "9901:9901"      # Port for Envoy's admin interface
    restart: no
    #environment:
      #- ENVOY_UID=0 # this works to run the scripts
      #- ENVOY_GID=101 # this works to run the scripts
    entrypoint: [ "/usr/local/bin/start-envoy.sh" ]
    command: [ "envoy", "-c", "/etc/envoy/envoy.yaml" ]
    networks:
      - envoy-network

  envoy-dev-windows:
    profiles:
      - windows
      - development
    image: envoyproxy/envoy:v1.30-latest
    volumes:
      - ../envoy/envoy_development_https.yaml:/etc/envoy/envoy.yaml
      - /d/certs:/certs # for https yaml
    labels:
      - "com.simulshift.description=Envoy Development Build"
      - "com.simulshift.version=1.0.0-dev"
    ports:
      - "443:443"        # Port for HTTPS traffic
      - "8080:8080"      # Port for HTTP traffic
      - "9901:9901"      # Port for Envoy's admin interface
      - "9902:9902"      # Port for rest api
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  envoy-network:
    external: true