services:
  # Chatbot
  chatbot-prod:
    image: alexpena/simulchatbot:latest
    profiles:
      - production
      - linux
    build:
      context: ${SIMULCHATBOT_PATH} # Directory containing Dockerfile.chatbot
    ports:
      - "8080:8082" # Map port for express server
      - "8083:8083" # Map port for fastify server
      - "9090:9090" # Map port 9090 for Main GRPC
      - "9095:9095" # Map port 9095 for Waifu GRPC
    volumes:
      - ${SIMULCHATBOT_LOGS}:/usr/src/app/logs # Optional: bind mount for logs if your app logs to files
    # Optional: Define commands or override the CMD defined in Dockerfile.chatbot
    command: "node dist/Runner.js --start-fastify"
    env_file:
      - ${SIMULCHATBOT_PATH}/.env # Path to your .env file
    networks:
      - envoy-network
networks:
  envoy-network:
    external: true