name: Deploy to Remote Server

on:
  push:
    branches:
      - master  # or the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/simulSsh-agent@v0.5.3
        with:
          # added to authorized keys on droplet and gave the secret to Github actions
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DROPLET }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no x@146.190.199.222 'cd ~/simulploy && git pull'
