name: Deploy to Remote Server

on:
  push:
    branches:
      - main  # or the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          # added to authorized keys on droplet and gave the secret to Github actions
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no user@remote_server 'cd ~/simulploy && git pull'
